id: I6B5C139C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T08:51:35+00:00'
last_modified: '2022-06-08T01:35:12.569573+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22202
  title: མདོ་ཁམས་པ་ཀརྨ་བསྟན་འཕེལ་རྣམ་ཐར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    41C8:
      image_group_id: I3030
      title: ''
      total_pages: 322
      order: 1
      base_file: 41C8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
