id: P004509
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W22202
  title: མདོ་ཁམས་པ་ཀརྨ་བསྟན་འཕེལ་རྣམ་ཐར
  author: ''
  volumes:
    7fdf28b2f2c14cceb6d6df4312230cc2:
      image_group_id: I3030
      title: ''
      volume_number: 1
      total_pages: 322
      base_file: v001.txt
